language: node_js
node_js:
    - "10"

services:
  - mysql

# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=test

# 在 install 前執行的指令
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ac_twitter_workspace_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - export JWT_SECRET=alphacamp

# 在執行測試之前的指令
before_script:
  - sequelize db:migrate

  deploy:
    provider: heroku
    api_key:
      secure: 1ff42a9b-5d57-4f14-b5d0-4bc3bc284652
    app: ac-simple-twitter-starter
    on:
      repo: whynotwilson/simple-twitter-express-starter
