version: 2.1
general:
  branches:
    only:
      - master
      - dev
      - hotfix
      - test

executors:
  default_test_environment:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo

commands:
  default_test_commands:
    description: "Test our application"
    steps:
      - run: 
          name: Install deps 
          command: npm install
      - run:
          name: Run tests
          command: npm test
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
        environment:
          NODE_ENV: test
    working_directory: ~/repo

    steps:
      # Init
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install migration kit
          command: npm install -g sequelize-cli
      - run:
          name: run local sequelize-cli migrate command
          commmand: npx sequelize db:migrate --env test
      - run:
          name: run test
          command: npm test

workflows:
  version: 2

  test:
    jobs:
      test