version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/postgres:10.1
    
    working_directory: ~/repo

    steps:
      # Init
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Test
      - run: sudo apt-get update
      - run: sudo apt install postgresql-client

      - run: psql -U postgres -h localhost -p 5432 -c "CREATE USER root;"
      - run: psql -U postgres -h localhost -p 5432 -c "ALTER USER root WITH SUPERUSER;"

      - run: npm run db:create
      - run: npm run db:migrate

      - run: npm test

    environment:
      NODE_ENV: test

workflows:
  version: 2

  test:
    jobs:
      test